spring:
  application:
    name: aims-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:aims-backend-super-secret-key-change-this-in-production-min-256-bits-required-for-hs256}
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 604800000 # 7 days
    issuer: aims-backend

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html

paypal:
  base-url: ${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}
  client-id: ASmKQU2F4OqhMexo_uPkJnEGe6v8KLBIdadBYuXeOPMV6ZfJ4CWkQ0omUynbNO5boOVyww7dk8op7Y1L
  client-secret: EHpV3RObVFJW5rQ6V0mpFbhV23j-SLolQdkTyS791sGaGc1c00PfWv1-clr1UxqceHzoeuzptfmzbUwz

vietqr:
  base-url: ${VIETQR_BASE_URL:https://api.vietqr.io}
  api-key: ${VIETQR_API_KEY:707e768d-b797-4a41-9f5c-6912bff7495b}
  client-id: ${VIETQR_CLIENT_ID:e2ded8cd-64b7-4b08-ae1d-0f9f810d5513}
  checksum-key: ${VIETQR_CHECKSUM_KEY:38deb0b3892fdcd7b578552d8e375fdeda902fc6528e38478daf534a3ee90702}
