spring:
  application:
    name: aims-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    user:
      email: admin
      password: admin
      roles: ADMIN,PRODUCT_MANAGER
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:aims-backend-super-secret-key-change-this-in-production-min-256-bits-required-for-hs256}
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 604800000 # 7 days
    issuer: aims-backend

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html

paypal:
  base-url: ${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}
  client-id: ASmKQU2F4OqhMexo_uPkJnEGe6v8KLBIdadBYuXeOPMV6ZfJ4CWkQ0omUynbNO5boOVyww7dk8op7Y1L
  client-secret: EHpV3RObVFJW5rQ6V0mpFbhV23j-SLolQdkTyS791sGaGc1c00PfWv1-clr1UxqceHzoeuzptfmzbUwz

vietqr:
  base-url: ${VIETQR_BASE_URL:https://sandbox.vietqr.io}
  api-key: ${VIETQR_API_KEY:4fb1795a-2db8-498a-bf0c-3ff01b032c44}
  client-id: ${VIETQR_CLIENT_ID:6dbe87b7-9931-45f1-a8ae-65ea78d29aca}
  checksum-key: ${VIETQR_CHECKSUM_KEY:d60df409c5edd74ce3f155208dbc86016ea96cf65fe8b77d00186eb624c24e1e}
